import { ArrowUpRight, ChevronDown, GitBranch, FolderOpen } from 'lucide-react';
import type { ProjectStory } from './portfolioContent';
import { RagPipeline } from './RagPipeline';

export const ProjectCard = ({project}:{project:ProjectStory}) => (
  <article id={project.id==='mcp'?'personal-projects':project.id} className={`project-story project-${project.id}`} aria-labelledby={`${project.id}-heading`}>
    <div className="project-label"><span className="project-number">{project.number}</span><span>{project.category}</span></div>
    <div className="project-main"><div className="project-copy"><h3 id={`${project.id}-heading`}>{project.title}</h3><p className="project-question">{project.question}</p><p>{project.contribution}</p><ul className="tech-tags" aria-label="Technologies">{project.stack.map(tech=><li key={tech}>{tech}</li>)}</ul></div>
      <aside className="project-evidence" aria-label="Documented outcome"><span className="margin-label">{project.id==='mcp'?'the connection':'in practice'}</span>{project.id==='mcp'?<div className="mcp-connection" aria-label="Assistant connects to Google Drive through MCP and OAuth"><span><GitBranch aria-hidden="true" size={20}/>Assistant</span><span className="connection-line" aria-hidden="true"/><span><FolderOpen aria-hidden="true" size={20}/>Drive files</span></div>:<div className="project-metrics">{project.metrics.map(metric=><div key={metric.label}><strong>{metric.value}</strong><span>{metric.label}</span></div>)}</div>}<p>{project.id==='rag'?'A production pipeline for educational content generation.':project.id==='tracker'?'A3C, a custom environment, and parallel learning.':'Google OAuth authentication · Model Context Protocol'}</p>{project.github&&<a className="text-link" href={project.github} target="_blank" rel="noopener noreferrer">Explore the repository <ArrowUpRight size={15} aria-hidden="true" /></a>}</aside>
    </div>
    <details className="project-details"><summary>Inside the project <ChevronDown size={17} aria-hidden="true" /></summary><div className="project-details-content"><div className="project-detail-grid"><div><h4>The approach</h4><p>{project.approach}</p></div><div><h4>The outcome</h4><p>{project.outcome}</p></div></div><ul className="detail-list">{project.details.map(detail=><li key={detail}>{detail}</li>)}</ul>{project.id==='rag'&&<RagPipeline />}{project.id==='tracker'&&<div className="tracking-concept"><p className="margin-label">Conceptual architecture · not a live benchmark</p><div className="tracking-flow"><span>MOT17 environment</span><span aria-hidden="true">→</span><div><span>Worker 01</span><span>Worker 02</span></div><span aria-hidden="true">→</span><span>Shared learning</span></div><p>Workers interact with a custom environment and contribute to the A3C learning process.</p></div>}</div></details>
  </article>
);
